apps/books_web/lib/books_web/router.ex
defmodule BooksWeb.Router do
  use BooksWeb, :router

  import BooksWeb.UserAuth

  #   FIXME: implement secure browser headers
  # if Mix.env() == :dev do
  #   @content_security_policy "default-src 'self' 'unsafe-eval' 'unsafe-inline'; " <>
  #     "connect-src ws://#{@host}:*; " <>
  #     "img-src 'self' blob: data:"
  # else
  #   @content_security_policy "default-src 'self'; connect-src wss://#{@host}; img-src 'self' blob:;"
  # end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, html: {BooksWeb.Layouts, :root}
    plug :put_layout, html: {BooksWeb.Layouts, :app}
    plug :protect_from_forgery
    #   FIXME: implement secure browser headers
    # plug :put_secure_browser_headers, %{"content-security-policy" => @content_security_policy}
    plug :put_secure_browser_headers
    plug :fetch_current_user
    plug :put_user_token
    plug RemoteIp, Application.get_all_env(:remote_ip)
    plug BooksWeb.Locale
  end

  pipeline :api do
    plug RemoteIp, Application.get_all_env(:remote_ip)
    plug :accepts, ["json"]
  end

  pipeline :admin do
    plug :menu
  end

  defp menu(conn, _params) do
    assigns = Map.put(conn.assigns, :conn, conn)
    assign(conn, :menu, BooksWeb.Layouts.menu(assigns))
  end

  scope "/admin", BooksAdmin do
    pipe_through [:browser, :require_admin, :admin]
    forward "/", Router
  end

  scope "/api/v1", BooksWeb do
    pipe_through :api

    # For Payment webhooks (from external APIs)
    post "/mailchimp", MailchimpController, :handle
    get "/mailchimp", MailchimpController, :handle
  end

  scope "/", BooksWeb do
    pipe_through :browser

    get "/", CatalogController, :index
    get "/catalog/:book_lang", CatalogController, :index
    get "/book/:book_slug", CatalogController, :book
    post "/book/:book_slug", CatalogController, :subscribe

    get "/cart", CartController, :index
    get "/cart/add/:format", CartController, :add
    get "/cart/rem/:format", CartController, :rem
    get "/cart/bundle/:slug", CartController, :bundle
    post "/cart", CartController, :payment
    put "/cart", CartController, :payment
    get "/cart/payment", CartController, :check_payment
    post "/cart/code", CartController, :discount

    get "/cart/payment/stripe/:id", StripeController, :index
    post "/cart/payment/stripe/:id", StripeController, :save

    get "/book/:token/:order/:format", DownloadController, :download

    get "/privacidad", LegalController, :privacy_es
    get "/politica-cookies", LegalController, :cookies_es
    get "/acuerdo-de-uso", LegalController, :tos_es
    get "/acerca-de", LegalController, :about_es

    get "/privacy", LegalController, :privacy_en
    get "/cookies", LegalController, :cookies_en
    get "/tos", LegalController, :tos_en
    get "/about", LegalController, :about_en

    get "/lang/:lang", LocaleController, :set_lang

    delete "/logout", UserSessionController, :delete
    get "/logout", UserSessionController, :logout
    get "/user-confirm", UserConfirmationController, :new
    post "/user-confirm", UserConfirmationController, :create
    get "/user-confirm/:token", UserConfirmationController, :edit
    post "/user-confirm/:token", UserConfirmationController, :update

    get "/posts", PostsController, :index
    get "/:year/:month/:day/:slug", PostsController, :show

    get "/landing/:slug", LandingController, :show
    post "/landing/:slug", LandingController, :subscribe
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: BooksWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", BooksWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/register", UserRegistrationController, :new
    # TODO: register using a subscritpion
    # post "/register", UserRegistrationController, :create
    get "/login", UserSessionController, :new
    post "/login", UserSessionController, :create
    get "/forgot-password", UserResetPasswordController, :new
    post "/forgot-password", UserResetPasswordController, :create
    get "/reset-password/:token", UserResetPasswordController, :edit
    put "/reset-password/:token", UserResetPasswordController, :update
  end

  scope "/", BooksWeb do
    pipe_through [:browser, :require_authenticated_user]

    live "/user-settings", UserSettingsLive.Edit, :edit
    live "/:lang/user-settings", UserSettingsLive.Edit, :edit

    get "/user-settings/subscribe/:book_slug", UserSettingsController, :subscribe
    get "/user-settings/unsubscribe/:book_slug", UserSettingsController, :unsubscribe
    get "/user-settings/confirm_email/:token", UserSettingsController, :confirm_email
    get "/bookshelf", UserBookshelfController, :index
    get "/bookshelf/download/:file_id", UserBookshelfController, :download
    get "/my-orders", CartController, :my_orders
    get "/my-order/:order_id", CartController, :my_order
    resources "/posts", PostsController, except: [:index, :show]
    post "/posts/:slug/comment", CommentsController, :create
  end

  ##  token for websocket from session (order)
  defp put_user_token(conn, _) do
    if cookie = conn.cookies["_books_key"] do
      token = Phoenix.Token.sign(conn, "cart socket", cookie)
      assign(conn, :user_token, token)
    else
      conn
    end
  end

  scope "/", BooksWeb do
    pipe_through :browser

    get "/en/*redirect", LocaleController, :set_lang_en
    get "/es/*redirect", LocaleController, :set_lang_es

    post "/en/*redirect", LocaleController, :set_lang_en
    post "/es/*redirect", LocaleController, :set_lang_es

    put "/en/*redirect", LocaleController, :set_lang_en
    put "/es/*redirect", LocaleController, :set_lang_es

    delete "/en/*redirect", LocaleController, :set_lang_en
    delete "/es/*redirect", LocaleController, :set_lang_es

    # keep always the last one
    get "/:slug", LandingController, :show
  end
end

apps/books_web/lib/books_web/controllers/cart_controller.ex
defmodule BooksWeb.CartController do
  use BooksWeb, :controller
  require Logger

  alias Books.Ads
  alias Books.{Cart, Payment, Shipping}
  alias Books.Cart.{Order, PaymentOption}

  @free_provider "4free"

  plug BooksWeb.SetOrder, except: ~w[
    change_payment_status
    payment
    check_payment
  ]a

  def index(conn, _params) do
    {id, conn} = BooksWeb.SetOrder.get_order_id(conn)
    order = Cart.get_order(id)
    changeset = Order.changeset(order, %{})

    payment_options =
      if Money.zero?(order.total_price) do
        [payment_option: Cart.PaymentOption.get_by_slug(@free_provider)]
      else
        [payment_options: PaymentOption.all()]
      end

    render(
      conn,
      default_opts(
        conn,
        order,
        [
          title: gettext("Cart"),
          changeset: changeset
        ] ++ payment_options
      )
    )
  end

  def discount(conn, params) do
    if offer = Ads.get_offer_by_code(params["offer"]["code"]) do
      {id, conn} = BooksWeb.SetOrder.get_order_id(conn)
      Cart.add_offer(id, offer)

      conn
      |> put_flash(:info, gettext("accepted code"))
      |> redirect(to: Routes.cart_path(conn, :index))
    else
      conn
      |> put_flash(:error, gettext("invalid code"))
      |> redirect(to: Routes.cart_path(conn, :index))
    end
  end

  def payment(conn, %_{slug: @free_provider}, order_id) do
    order = Cart.get_order(order_id)

    if Money.zero?(order.total_price) do
      info = %{
        "payer" => %{
          "payer_info" => %{
            "email" => order.email,
            "firt_name" => order.first_name,
            "last_name" => order.last_name
          }
        }
      }

      :ok = Cart.pay(order_id, info, conn.assigns[:locale])
      order = Cart.get_order(order_id)

      opts =
        default_opts(conn,
          title: gettext("Payment successfully"),
          hashid: order_id,
          files: Cart.get_files(order_id),
          preventa: Cart.presale?(order_id),
          order: order
        )

      conn
      |> put_session(:order_id, nil)
      |> render("paid.html", opts)
    else
      Logger.error(
        "error in payment: order #{order_id} hasn't payment method and it's not for free"
      )

      Cart.cancel(order_id)

      opts =
        default_opts(conn,
          title: gettext("Payment error"),
          hashid: nil,
          formats: nil
        )

      conn
      |> put_session(:order_id, nil)
      |> render("payment_error.html", opts)
    end
  end

  def payment(conn, %_{slug: provider}, order_id) do
    order = Cart.get_order(order_id)
    f = &BooksWeb.Payment.get_payment_url(conn, &1)
    build_payment = Payment.build_payment(provider, order, f, conn.assigns[:locale])

    with {:ok, payment} <- Payment.create_payment(provider, build_payment),
         {:ok, [link | _], token} <- BooksWeb.Payment.get_redirect(provider, conn, payment) do
      Cart.set_token(order_id, token)
      Cart.set_payment_id(order_id, payment.body["id"])

      conn
      |> put_session(:order_id, nil)
      |> redirect(external: link)
    else
      error ->
        Logger.error("error in payment: #{inspect(error)}")
        Cart.cancel(order_id)

        opts =
          default_opts(conn,
            title: gettext("Payment error"),
            hashid: nil,
            formats: nil
          )

        conn
        |> put_session(:order_id, nil)
        |> render("payment_error.html", opts)
    end
  end

  def payment(conn, params) do
    {id, conn} = BooksWeb.SetOrder.get_order_id(conn)
    amount = Shipping.get_amount(params["order"]["shipping_country"])
    params_order = Map.put(params["order"], "shipping_amount", amount)

    if Cart.process(id, params_order) do
      payment(conn, Cart.get_payment_option(id), id)
    else
      order = Cart.get_order(id)
      changeset = Order.changeset(order, params_order)

      changeset =
        case Ecto.Changeset.apply_action(changeset, :insert) do
          {:error, changeset} -> changeset
          {:ok, _order} -> changeset
        end

      payment_options =
        if Money.zero?(order.total_price) do
          [payment_option: Cart.PaymentOption.get_by_slug(@free_provider)]
        else
          [payment_options: PaymentOption.all()]
        end

      opts = [{:changeset, changeset} | payment_options]

      conn
      |> put_session(:order_id, id)
      |> put_flash(:error, gettext("Provide full data and accept the terms of service, please"))
      |> render("index.html", default_opts(order, opts))
    end
  end

  def check_payment(conn, %{"cancel" => _, "token" => token, "provider" => provider}) do
    Logger.error("order cancelled in #{provider} #{token}")

    if order_id = Cart.get_by_token(token) do
      Cart.cancel(order_id)
    end

    opts =
      default_opts(conn,
        title: gettext("Payment cancelled"),
        hashid: nil,
        formats: nil
      )

    render(conn, "payment_cancelled.html", opts)
  end

  def check_payment(conn, %{"token" => token, "provider" => provider}) do
    if order_id = Cart.get_by_token(token) do
      payment_id = Cart.get_payment_id(order_id)

      case Payment.check_payment(provider, payment_id) do
        {:ok, full_order} ->
          :ok = Cart.pay(order_id, full_order, conn.assigns[:locale])
          order = Cart.get_order(order_id)

          opts =
            default_opts(conn,
              title: gettext("Payment successfully"),
              hashid: order_id,
              files: Cart.get_files(order_id),
              preventa: Cart.presale?(order_id),
              order: order
            )

          conn
          |> put_session(:order_id, nil)
          |> render("paid.html", opts)

        {:error, :cancelled} ->
          Logger.error("order not found by #{provider} #{token} was cancelled")
          Cart.cancel(order_id)

          opts =
            default_opts(conn,
              title: gettext("Payment cancelled"),
              hashid: nil,
              formats: nil
            )

          conn
          |> put_session(:order_id, nil)
          |> render("payment_cancelled.html", opts)

        {:error, :notfound} ->
          Logger.error("order not found by #{provider} #{token}")

          opts =
            default_opts(conn,
              title: gettext("Payment not found"),
              token: token,
              hashid: nil,
              formats: nil
            )

          conn
          |> put_session(:order_id, nil)
          |> render("payment_not_found.html", opts)

        {:error, reason} ->
          Logger.error("order not found by #{provider} #{token}: #{inspect(reason)}")

          opts =
            default_opts(conn,
              title: gettext("Payment error"),
              hashid: nil,
              formats: nil
            )

          conn
          |> put_session(:order_id, nil)
          |> render("payment_error.html", opts)
      end
    else
      Logger.warning("not found token: #{token}")

      opts =
        default_opts(conn,
          title: gettext("Payment not found"),
          token: nil,
          hashid: nil,
          formats: nil
        )

      conn
      |> put_session(:order_id, nil)
      |> render("payment_not_found.html", opts)
    end
  end

  def change_payment_status(conn, %{"provider" => provider, "update" => _, "id" => id}) do
    Logger.info("[#{provider}] received update for request #{id}")

    case Payment.get_payment(provider, id) do
      {:ok, payment} -> Logger.info("[#{provider}] info: #{inspect(payment)}")
      error -> Logger.error("[#{provider}] info: #{inspect(error)}")
    end

    render(conn, "change_payment_status", status: "ok")
  end

  defp return_to(conn, params) do
    with nil <- params["return-to"],
         [] <- get_req_header(conn, "referer") do
      Routes.catalog_path(conn, :index)
    else
      [url] -> URI.new!(url).path
      path when is_binary(path) -> path
    end
  end

  defp rem_item(conn, format_id) do
    {order_id, conn} = BooksWeb.SetOrder.get_order_id(conn)
    Cart.rem_item(order_id, format_id)
    conn
  end

  def rem(conn, %{"format" => format_id} = params) do
    conn
    |> rem_item(format_id)
    |> put_resp_header("x-robots-tag", "noindex")
    |> redirect(to: return_to(conn, params))
  end

  defp add_item(conn, format_id) do
    {order_id, conn} = BooksWeb.SetOrder.get_order_id(conn)
    Cart.add_item(order_id, format_id)
    conn
  end

  defp add_items(conn, formats) do
    {order_id, conn} = BooksWeb.SetOrder.get_order_id(conn)
    Enum.each(formats, &Cart.add_item(order_id, &1.id))
    conn
  end

  def add(conn, %{"format" => format_id} = params) do
    conn
    |> add_item(format_id)
    |> put_flash(
      :info,
      gettext("Added successfully the item to the <a href='%{url}'>cart</a>",
        url: Routes.cart_path(conn, :index)
      )
    )
    |> put_resp_header("x-robots-tag", "noindex")
    |> redirect(to: return_to(conn, params))
  end

  def bundle(conn, %{"slug" => slug}) do
    bundle = Ads.get_bundle_by_slug!(slug)

    conn
    |> add_items(bundle.formats)
    |> put_resp_header("x-robots-tag", "noindex")
    |> redirect(to: Routes.cart_path(conn, :index))
  end

  def my_orders(conn, _params) do
    current_user = conn.assigns[:current_user]

    opts =
      default_opts(
        conn,
        title: gettext("My Orders"),
        my_orders: Cart.list_orders_by_email(current_user.email)
      )

    render(conn, "my_orders.html", opts)
  end

  def my_order(conn, %{"order_id" => order_id}) do
    current_user = conn.assigns[:current_user]
    order = Cart.ensure_get_order(order_id)

    if order != nil and order.email == current_user.email do
      opts =
        default_opts(
          conn,
          title: gettext("My Order: %{order_id}", order_id: order_id),
          my_order: order
        )

      render(conn, "my_order.html", opts)
    else
      raise BooksWeb.ErrorNotFound, message: gettext("Order not found")
    end
  end
end

apps/books_web/lib/books_web/controllers/download_html.ex
defmodule BooksWeb.DownloadHTML do
  use BooksWeb, :html
  embed_templates "download_html/*"
end

apps/books_web/lib/books_web/controllers/error_html.ex
defmodule BooksWeb.ErrorHTML do
  use BooksWeb, :html

  # If you want to customize your error pages,
  # uncomment the embed_templates/1 call below
  # and add pages to the error directory:
  #
  #   * lib/books_web/controllers/error_html/404.heex
  #   * lib/books_web/controllers/error_html/500.heex
  #
  embed_templates "error_html/*"

  # The default is to render a plain text page based on
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def render(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

apps/books_web/lib/books_web/controllers/landing_html.ex
defmodule BooksWeb.LandingHTML do
  use BooksWeb, :html
  import BooksWeb.MarkdownHelpers

  def get_image(type, book) do
    if String.ends_with?(book.slug, "-#{book.edition}ed") do
      "#{type}-#{book.slug}.png"
    else
      "#{type}-#{book.slug}-#{book.edition}ed.png"
    end
  end

  embed_templates "landing_html/*"
end

apps/books_web/lib/books_web/controllers/posts_html/card.heex
<div class="card">
  <div class="card-content">
    <div class="media">
      <div class="media-left">
        <figure class="image is-64x64">
          <img
            alt={gettext("featured image")}
            src={static_path(@conn, "/images/posts/#{@post.featured_image}")}
          />
        </figure>
      </div>
      <div class="media-content">
        <p class="title is-4 project-name">
          <%= link(get_title(@post), to: post_path(@conn, @post)) %>
        </p>
        <p class="subtitle is-6 project-url"><%= get_date(@post) %></p>
      </div>
    </div>
    <div class="content project-description">
      <%= raw(@post.excerpt) %>
    </div>
  </div>
</div>

apps/books_web/lib/books_web/controllers/posts_html/custom_form.heex
<div class="column is-10 is-offset-1">
  <.form :let={f} for={@changeset} action={@action}>
    <div class="tabs">
      <ul>
        <li class="tab-item is-active" data-id="tab-main"><a><%= gettext("Main") %></a></li>
        <li class="tab-item" data-id="tab-images"><a><%= gettext("Images") %></a></li>
        <li class="tab-item" data-id="tab-advanced"><a><%= gettext("Advanced") %></a></li>
      </ul>
    </div>

    <div id="tab-main" class="tab-section">
      <.text_input form={f} name={:title} title={gettext("Title")} required={true} />
      <.text_input form={f} name={:subtitle} title={gettext("Subtitle")} />
      <.select
        form={f}
        name={:category_id}
        title={gettext("Category")}
        values={@categories}
        required={true}
        prompt={gettext("Choose one...")}
      />
      <.tags_input
        form={f}
        name={:tags_text}
        title={gettext("Tags")}
        data-values={@tags}
        data-selectable="true"
        data-free-input="true"
        data-search-on="text"
      />
      <.textarea form={f} name={:content} title={gettext("Content")} class="easymde" />
    </div>

    <div id="tab-advanced" class="tab-section is-hidden">
      <.text_input form={f} name={:slug} title={gettext("Slug")} />
      <.datetime form={f} name={:inserted_at} title={gettext("Publish date")} />
      <.select form={f} name={:lang} title={gettext("Language")} values={@languages} />
      <.textarea
        form={f}
        name={:excerpt}
        title={gettext("Excerpt")}
        class="easymde"
        data-height="200px"
      >
        <:help>
          <%= gettext(
            "If you specified a <!--more--> tag inside of the content, this excerpt will be replaced for the indicated content."
          ) %>
        </:help>
      </.textarea>
      <.select form={f} name={:books} title={gettext("Books")} values={@book_list} multiple={true}>
        <:help>
          <%= gettext(
            "If any book is selected the post is converted to private and only shown if the user belongs any of these books."
          ) %>
        </:help>
      </.select>
    </div>

    <div id="tab-images" class="tab-section is-hidden">
      <.select
        form={f}
        name={:featured_image}
        title={gettext("Featured image")}
        values={@featured}
        prompt={gettext("No image selected")}
      >
        <help><%= gettext("(Optional) Choose an existing featured image") %></help>
      </.select>
      <.select
        form={f}
        name={:background_image}
        title={gettext("Background image")}
        values={@backgrounds}
        prompt={gettext("No image selected")}
      >
        <help><%= gettext("(Optional) Choose an existing background image") %></help>
      </.select>
    </div>

    <div class="mt-5">
      <.submit_form title={gettext("Save")} />
    </div>
  </.form>
</div>

apps/books_web/lib/books_web/controllers/posts_html/edit.heex
<div class="content">
  <div class="columns">
    <div class="column is-10 is-offset-1">
      <h1 class="title is-2"><%= gettext("Edit Post") %></h1>
    </div>
  </div>
  <div class="columns">
    <.custom_form {Map.put(assigns, :action, Routes.posts_path(@conn, :update, @post.id))} />
  </div>
</div>

apps/books_web/lib/books_web/controllers/posts_html/index.heex
<div class="content">
  <% {recent_posts, more_posts} = Enum.split(@posts.entries, @recent_posts) %>
  <%= if @recent_posts > 0 do %>
    <section class="hero">
      <div class="hero-body">
        <div class="container">
          <%= for {post, i} <- Enum.with_index(recent_posts) do %>
            <%= if i > 0 do %>
              <div class="is-divider"></div>
            <% end %>
            <section class="section">
              <div class="columns">
                <div class="column is-4-widescreen is-offset-1-widescreen">
                  <figure class="image is-featured">
                    <img
                      alt={gettext("featured image")}
                      src={"/images/posts/#{post.featured_image || "unknown.jpg"}"}
                    />
                  </figure>
                </div>
                <div class="column is-7">
                  <div class="content is-medium">
                    <h2 class="subtitle is-4">
                      <a href="#">
                                        <span class={"tag is-#{post.category.color} is-uppercase"}>
                                            <%= post.category.name[@locale] %>
                                        </span>
                                    </a>&nbsp;
                      <%= if post.private do %>
                        <i class="fas fa-lock"></i>&nbsp;
                      <% end %>
                      <%= get_date(post) %>&nbsp;
                      <span class="tag">
                        <%= get_reading_min(post) %> <%= gettext("reading minutes") %>
                      </span>
                    </h2>
                    <h1 class="title">
                      <%= link(get_title(post), to: post_path(@conn, post)) %>
                    </h1>
                    <span class="is-flex is-flex-wrap-wrap ml-2 is-line-height-wider">
                      <%= link to: post_path(@conn, post) <> "#comments" do %>
                        <span class="tag is-ghost">
                                            <i class="fas fa-comment"></i>&nbsp;
                                            <%= length(post.comments) %>
                                        </span>&nbsp;
                      <% end %>
                      <%= for tag <- post.tags do %>
                        <%= link to: "#" do %>
                          <span class="tag is-black">
                                            <i class="fas fa-tag"></i>&nbsp;
                                            <%= tag.name %>
                                        </span>&nbsp;
                        <% end %>
                      <% end %>
                    </span>
                    <p><%= raw(to_html(get_excerpt(post))) %></p>
                    <p>
                      <%= link to: post_path(@conn, post) do %>
                        <%= gettext("Read more") %> <i class="fas fa-arrow-right"></i>
                      <% end %>
                    </p>
                  </div>
                </div>
              </div>
            </section>
          <% end %>
        </div>
      </div>
    </section>
  <% end %>

  <section class="hero">
    <%= if @recent_posts == 0 do %>
      <.paginate page={@posts} url={&Routes.posts_path(@conn, :index, page: to_string(&1))} />
    <% end %>
    <div class="hero-body">
      <div class="container">
        <section class="section">
          <div class="columns is-multiline">
            <%= for post <- more_posts do %>
              <div class="column is-5-desktop is-offset-1-desktop is-6-tablet is-12-mobile">
                <div class="content is-medium">
                  <figure class="image is-100x100 is-pulled-left ml-0 mt-0 mr-5 mb-2">
                    <img
                      alt={gettext("featured image")}
                      src={"/images/posts/#{post.featured_image || "unknown.jpg"}"}
                    />
                  </figure>
                  <h2 class="subtitle is-5 has-text-grey">
                    <a href="#">
                                        <span class={"tag is-#{post.category.color} is-uppercase"}>
                                            <%= post.category.name[@locale] %>
                                        </span>
                                    </a>&nbsp;
                    <%= if post.private do %>
                      <i class="fas fa-lock"></i>&nbsp;
                    <% end %>
                    <%= get_date(post) %>&nbsp;
                    <span class="tag">
                      <%= get_reading_min(post) %> <%= gettext("reading minutes") %>
                    </span>
                  </h2>
                  <h1 class="title has-text-black is-3">
                    <%= link(get_title(post), to: post_path(@conn, post)) %>
                  </h1>
                  <span class="is-flex is-flex-wrap-wrap ml-2 is-line-height-wider">
                    <%= link to: post_path(@conn, post) <> "#comments" do %>
                      <span class="tag is-ghost">
                                            <i class="fas fa-comment"></i>&nbsp;
                                            <%= length(post.comments) %>
                                        </span>&nbsp;
                    <% end %>
                    <%= for tag <- post.tags do %>
                      <%= link to: "#" do %>
                        <span class="tag is-black">
                                            <i class="fas fa-tag"></i>&nbsp;
                                            <%= tag.name %>
                                        </span>&nbsp;
                      <% end %>
                    <% end %>
                  </span>
                  <p class="has-text-dark"><%= raw(to_html(get_excerpt(post))) %></p>
                  <p>
                    <a href={post_path(@conn, post)}>
                      <%= gettext("Read more") %> <i class="fas fa-arrow-right"></i>
                    </a>
                  </p>
                </div>
                <div class="is-divider"></div>
              </div>
            <% end %>
          </div>
        </section>
      </div>
    </div>
    <.paginate page={@posts} url={&Routes.posts_path(@conn, :index, page: to_string(&1))} />
  </section>
</div>

apps/books_web/lib/books_web/controllers/posts_html/new.heex
<div class="content">
  <div class="columns">
    <div class="column is-10 is-offset-1">
      <h1 class="title is-2"><%= gettext("New Post") %></h1>
    </div>
  </div>
  <div class="columns">
    <.custom_form {Map.put(assigns, :action, Routes.posts_path(@conn, :create))} />
  </div>
</div>